### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Neizvestnyj** [Neizvestnyj/stl-to-obj#4]
- [x] 1. To make the `convert` function not freeze the main python thread, the current implementation causes the `kivy` window to hang. It is expected that when using it, the command execution sequence will remain the same exactly:

    ```py
    from stl2obj import Stl2Obj
    
    print(0)
    Stl2Obj().convert(stl, obj)
    print(2)
    ```
    output:
    ```
    >> 0
    >> 1
    >> 2
    ```

- [x] 2. To make the values of the `progress` function in `progress.cpp` passed to python, after which it would be possible to change the graphical `kivy` progressbar.

- [x] 3. Add **android** recipe, may be something like [this](https://github.com/Neizvestnyj/python_c_plus_plus/tree/master/recipes/android)

- [ ] 4. Add **ios** recipe, may be something like [this](https://github.com/Neizvestnyj/python_c_plus_plus/tree/master/recipes/ios)

- [ ] 5. Add ci for multiply python versions and architectures (python 3.7 - 3.11, archs x86, x64)
